- name: Playbook de Teste - Verificar Uptime
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "{{ usuario }}"
    ansible_host: "{{ servidor_ip }}"
    ansible_ssh_private_key_file: "{{ chave_path }}"
  tasks:
    - name: Executar comando 'uptime'
      shell: uptime
      register: uptime_result

    - name: Exibir resultado do uptime
      debug:
        msg: "Uptime do servidor {{ servidor_ip }}: {{ uptime_result.stdout }}"
